### ISSUE TITLE
All implementations should be disabled if user disables Force Touch in Settings.app

### ISSUE THREAD

**Issue by gtranchedone** [justeat/JustPeek#2]
### Issue

If a user disables Force Touch interactions in the Settings app, JustPeek shouldn't fallback to the replacement implementation, but just ignore the command.
### Blocker

It currently doesn't seem to be there any way to tell whether the force touch is generally unavailable or if it has been disabled.

**Comment by fpg1503** [comment]
This may be a silly suggestion but can't you just check the device model?

**Comment by gtranchedone** [comment]
Ideally, I would prefer to avoid hard coding device models. However, yes, it might work.

**Comment by federicocappelli-je** [comment]
@fpg1503 @gtranchedone this library is now obsolete and not supported anymore, I'm going to close this PR.
